server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1q2w3e4r
    driver-class-name: org.mariadb.jdbc.Driver

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

  rabbitmq:
    host: localhost
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

token:
  secret: jwt-token-secret
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

estsoft:
  oauth:
    server: http://localhost:8081
    client:
      id: root
      secret: root